version: '3.8'

services:
  # API Application para produção
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao-produtos-api-prod
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      # As variáveis abaixo devem ser configuradas no Render
      # ConnectionStrings__MongoDB: ${MONGODB_CONNECTION_STRING}
      # MongoDB__DatabaseName: ${MONGODB_DATABASE_NAME}
      # JWT__Secret: ${JWT_SECRET}
      # JWT__Issuer: ${JWT_ISSUER}
      # JWT__Audience: ${JWT_AUDIENCE}
      # CORS__AllowedOrigins: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s