version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: gestao-produtos-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: GestaoProdutosDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - gestao-produtos-network

  # API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao-produtos-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDB: mongodb+srv://gestaoProdutosBD:427931%40%21%40@cluster0.y60kygq.mongodb.net/GestaoProdutosDB?retryWrites=true&w=majority&appName=Cluster0
      ConnectionStrings__Redis: redis:6379
      MongoDB__DatabaseName: GestaoProdutosDB
      JWT__Secret: sua-chave-super-secreta-para-desenvolvimento-com-pelo-menos-32-caracteres
      JWT__Issuer: GestaoProdutosAPI
      JWT__Audience: GestaoProdutosApp
      CORS__AllowedOrigins: http://localhost:4200,http://localhost:4201,https://localhost:4200,https://localhost:4201
    ports:
      - "5000:8080"
    depends_on:
      - redis
    networks:
      - gestao-produtos-network
    volumes:
      - ./logs:/app/logs

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gestao-produtos-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gestao-produtos-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB Express (Interface web para MongoDB - opcional)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: gestao-produtos-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - gestao-produtos-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  gestao-produtos-network:
    driver: bridge